### ISSUE TITLE
Crashes Quixel Bridge in UE5

### ISSUE THREAD

**Issue by Ty-lerCox** [getnamo/BLUI-Unreal#65]
When BLUI is enabled, and I open Quixel Bridge from UE5 pane, it crashes the engine:

LoginId:5f4593dd43ad5f76c4fd729cfe2e4a5f
EpicAccountId:13e6f5f2674942c79bc67b4c0bd75121

Assertion failed: bSuccess [File:D:/build/++UE5/Sync/Engine/Source/Runtime/WebBrowser/Private/WebBrowserSingleton.cpp] [Line: 344]

UnrealEditor_WebBrowser
UnrealEditor_WebBrowser
UnrealEditor_Bridge
UnrealEditor_Bridge
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
user32
user32
UnrealEditor_ApplicationCore
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by getnamo** [comment]
Likely because quixel bridge uses the built-in [webbrowser](https://docs.unrealengine.com/4.26/en-US/API/Runtime/WebBrowser/) for its UI which uses CEF under the hood. These two have been incompatible for quite a while and you typically disable the built-in module to use BLUI. You may need to use webbrowser module instead if your use case requires it.

**Comment by YousefBadr** [comment]
I just ran into this issue too, had to disable bridge

**Comment by getnamo** [comment]
Closing in favor of https://github.com/getnamo/BLUI-Unreal/issues/80
